### ISSUE TITLE
Authorship and background unclear

### ISSUE THREAD

**Issue by peterjc** [nickp60/barrnap-python#1]
Am I right in thinking this is a port of Torsten Seemann (@tseemann)'s Perl tool barrnap https://github.com/tseemann/barrnap into Python by you Nick (@nickp60)?

If so, this seems OK in principle from a licensing point of view, but the README needs to be much clearer, and I would suggest adding your name as a co-author. Torsten likely will have some comments on how to clarify things further to avoid end user confusion.

(Separately, what is the goal here? I could understand if you were exposing the internals of the tool as callable functions for use within a larger Python project via ``import``, but a simple port seems to have little benefit given the original is still maintained)

**Comment by nickp60** [comment]
Yes, thats correct.

This is due to the fact that 100% of my riboSeed users (n=3 haha) have asked me to help trouble shoot issues relating to barrnap installation.  At first, this was due to the Time::Piece lib being _missing_, which is now a more cryptic related error of:
    
     perl: symbol lookup error: /home/nw42839/perl5/lib/perl5/x86_64-linux-thread-multi/auto/Time/Piece/Piece.so: undefined symbol: Perl_Istack_sp_ptr

I emailed Torsten this past spring, so he is aware of the project.  He did not want to maintain two versions of barrnap, so he did not want a pull request submitted.  I haven't heard back after offering to maintain it.

I will update the readme to hopefully clarify that.

**Comment by peterjc** [comment]
That new introduction at the start of the README is a big improvement, thanks!

(And I sympathise with Perl installation issues - its like Python in that usually it just works, but when it doesn't it can be very frustrating for a non-expert to solve)

**Comment by nickp60** [comment]
Great, thanks for noting the need for clarification!
